services:
  watch-batch-transcode:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: watch-batch-transcode
    environment:
      # User and group ID for file permissions (important for volume mounts)
      # Replace with your user and group ids. use the 'id' command
      - PUID=1000
      - PGID=1000

      # Timezone setting (optional, for correct timestamps in logs and csv)
      # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - TZ=Europe/Warsaw # America/New_York, Asia/Tokyo

      # Video codec to use (eg. libx265, libx264)
      # - VIDEO_CODEC=libx265
      # Constant rate factor (CRF) for video quality (lower = higher quality/size, higher = lower quality/size)
      # sane range for libx265 is 18-24.
      # - VIDEO_CRF=24
      # Video encoding preset (controls speed vs compression efficiency)
      # Options for libx265/libx264: ultrafast, superfast, veryfast, faster, fast, medium, slow, slower, veryslow, placebo
      # Slower presets give better compression at the same CRF, but take much longer.
      # - VIDEO_PRESET=medium

      # Audio codec to use (eg. libopus, aac, ac3)
      # - AUDIO_CODEC=libopus
      # Audio bitrate (eg. 96k, 128k, 192k)
      # - AUDIO_BITRATE=96k

      # ntfy.sh topic for notifications (optional: uncomment and replace with your topic)
      # Get a topic from ntfy.sh or your own ntfy server.
      # - NTFY_TOPIC=replace_with_your_own_topic
      # Custom ntfy.sh server instance (optional: uncomment and replace with your server url)
      # - NTFY_SERVER="https://your.ntfy.server"

      # Uncomment this to delete source files after processing. Setting this value to ANYTHING will enable it
      # - DELETE_AFTER=1

    volumes:
      # Source directory -> where you place video files to be processed
      - ./data/sources:/sources:rw

      # Processed sources directory: original files are moved here after being picked up
      # They remain here by default after successful processing. Check delete_after env var
      - ./data/sources_processed:/sources_processed:rw

      # Completed directory: successfully transcoded mp4 files and the CSV log are placed here.
      - ./data/completed:/completed:rw

      # Failed directory: Original files that failed all processing attempts are moved here.
      - ./data/failed:/failed:rw

      # The /tmp directory is ephmeral but you might wanna map it if you're dealing with extremely large files
      # - ./data/tmp:/tmp:rw

    restart: unless-stopped

    # Resource limits (optional: uncomment to limit CPU and memory usage)
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2.0' # Limit to 2 CPU cores
    #       memory: '4G' # Limit to 4GB of RAM
